Parameters:
    HttpApiName:
      Type: String
      Default: my-api

Resources:
  HttpApi:
  Type: AWS::ApiGatewayV2::Api
  Properties:
    Name: !Ref HttpApiName
    Description: Lambda proxy using quick create
    ProtocolType: HTTP
    Target: arn:aws:apigateway:{AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:{AWS::Region}:{AWS::AccountId}:function:{function-name}/invocations
